// <auto-generated />
using AutoAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoAPI.Migrations
{
    [DbContext(typeof(DbEngineContext))]
    [Migration("20221115113008_CambioNomeTableAcquirente")]
    partial class CambioNomeTableAcquirente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoAPI.Model.Acquirente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("acquirente");
                });

            modelBuilder.Entity("AutoAPI.Model.Auto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Casa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("acquirenteID")
                        .HasColumnType("int");

                    b.Property<string>("modello")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("acquirenteID");

                    b.ToTable("automobili");
                });

            modelBuilder.Entity("AutoAPI.Model.Auto", b =>
                {
                    b.HasOne("AutoAPI.Model.Acquirente", "acquirente")
                        .WithMany()
                        .HasForeignKey("acquirenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("acquirente");
                });
#pragma warning restore 612, 618
        }
    }
}
